base_url = "https://tb.saop.cc"

title = "图吧工具箱 - 纯净的硬件检测工具合集"
description = "图吧工具箱（全称图拉丁吧硬件检测工具箱）是一款开源、免费、绿色、纯净的硬件检测工具合集，专为图钉及所有DIY爱好者打造，内含常用硬件测试与检测工具，是月工JS的必备利器！"

default_language = "zh"

compile_sass = true

minify_html = true

generate_feeds = true
